config/routes.rb
Rails.application.routes.draw do
  resources :art_galleries
  root :to => 'art_galleries#index'
end

app/models/art_gallery.rb
# == Schema Information
#
# Table name: art_galleries
#
#  id       :integer          not null, primary key
#  name     :string(255)
#  location :string(255)
#  avatar   :text
#

class ArtGallery < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/art_galleries_controller.rb
class ArtGalleriesController < ApplicationController
  before_action :set_art_gallery, only: [:show, :edit, :update, :destroy]

  # GET /art_galleries
  # GET /art_galleries.json
  def index
    @art_galleries = ArtGallery.all
  end

  # GET /art_galleries/1
  # GET /art_galleries/1.json
  def show
  end

  # GET /art_galleries/new
  def new
    @art_gallery = ArtGallery.new
  end

  # GET /art_galleries/1/edit
  def edit
  end

  # POST /art_galleries
  # POST /art_galleries.json
  def create
    @art_gallery = ArtGallery.new(art_gallery_params)

    respond_to do |format|
      if @art_gallery.save
        format.html { redirect_to @art_gallery, notice: 'Art gallery was successfully created.' }
        format.json { render :show, status: :created, location: @art_gallery }
      else
        format.html { render :new }
        format.json { render json: @art_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /art_galleries/1
  # PATCH/PUT /art_galleries/1.json
  def update
    respond_to do |format|
      if @art_gallery.update(art_gallery_params)
        format.html { redirect_to @art_gallery, notice: 'Art gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @art_gallery }
      else
        format.html { render :edit }
        format.json { render json: @art_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /art_galleries/1
  # DELETE /art_galleries/1.json
  def destroy
    @art_gallery.destroy
    respond_to do |format|
      format.html { redirect_to art_galleries_url, notice: 'Art gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_gallery
      @art_gallery = ArtGallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_gallery_params
      params.require(:art_gallery).permit(:name, :location, :avatar, :remote_avatar_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_galleries_helper.rb
module ArtGalleriesHelper
end

app/views/art_galleries/_form.html.erb
<%= form_for(@art_gallery, :html => {:multipart => true})  do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, :accept => "image/gif, image/jpeg, image/svg, image/jpg, image/png", required: :required %>
  </div>
  <div class="field">
    <%= f.label :remote_avatar_url, "or image URL" %><br />
    <%= f.text_field :remote_avatar_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/art_galleries/edit.html.erb
<h1>Editing art_gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @art_gallery %> |
<%= link_to 'Back', art_galleries_path %>

app/views/art_galleries/index.html.erb
<h1>Listing art_galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @art_galleries.each do |art_gallery| %>
      <tr>
        <td><%= art_gallery.name %></td>
        <td><%= art_gallery.location %></td>
        <td><%= image_tag art_gallery.avatar %></td>
        <td><%= link_to 'Show', art_gallery %></td>
        <td><%= link_to 'Edit', edit_art_gallery_path(art_gallery) %></td>
        <td><%= link_to 'Destroy', art_gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Art gallery', new_art_gallery_path %>

app/views/art_galleries/new.html.erb
<h1>New art_gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', art_galleries_path %>

app/views/art_galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @art_gallery.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @art_gallery.location %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @art_gallery.avatar %>
</p>

<%= link_to 'Edit', edit_art_gallery_path(@art_gallery) %> |
<%= link_to 'Back', art_galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrierwavedemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>